### ISSUE TITLE
Replace setup links if they already exist?

### ISSUE THREAD

**Issue by jvkersch** [unipept/umgap#5]
First off, this is probably the easiest installable bioinformatics tool I've come across 👍 

When running `umgap-setup.sh`, would it be possible to replace the symbolic links to the taxonomy file and indices if they already exist (that is, use `ln -sf`)? That would make it a little easier to resume `umgap-setup.sh` on a partially downloaded set of files.

**Comment by ninewise** [comment]
Yeah, fair point; I'll make the change this weekend probably.

**Comment by jvkersch** [comment]
Thanks!  🙏

**Comment by ninewise** [comment]
Added in dd55de4a567fb052644fbff98a089e3a7e4b5ae2.
